### ISSUE TITLE
move repo

### ISSUE THREAD

**Issue by ghost** [waldbauer-certat/intelmq-docker#4]
move repo to github.com/certat

**Comment by waldbauer-certat** [comment]
Successfully moved to https://github.com/certat/intelmq-docker

**Comment by waldbauer-certat** [comment]
Repository fully merged with new repository https://github.com/certat/intelmq-docker/commit/eb1473b069953fdd79b843398f72d801bf29b6a7

Closing this issue, as it has been resolved :+1:
